In [ ]:
%matplotlib inline
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import sklearn
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from google.colab import drive
from sklearn import naive_bayes

from google.colab import drive
drive.mount('/content/drive',force_remount=True)
data=open('/content/drive/My Drive/Colab Notebooks/Thesis Data test.csv')


Mounted at /content/drive


In [ ]:
words=[]
i=0
for lines in data:
    if lines[0] !=';' and lines[0] != '\n':
        words.append(lines.strip())


In [ ]:
vect=CountVectorizer() ##Convert a collection of text documents to a matrix of token counts
vect.fit(words) #creates dict. by series of tokens

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [ ]:
print("Vocabulary size: {}".format(len(vect.vocabulary_)))
print("Vocabulary content:\n {}".format(vect.vocabulary_))

Vocabulary size: 1266
Vocabulary content:
 {'sentence': 993, 'sentiment': 995, 'it': 627, 'good': 501, 'teachers': 1109, 'can': 157, 'judge': 634, 'us': 1197, 'properly': 899, 'through': 1148, 'this': 1144, 'system': 1090, 'the': 1126, 'focus': 455, 'on': 776, 'outcomes': 802, 'creates': 235, 'clear': 184, 'expectation': 406, 'of': 771, 'what': 1227, 'needs': 751, 'to': 1153, 'be': 121, 'accomplished': 11, 'by': 154, 'end': 348, 'course': 229, 'not': 758, 'curriculum': 248, 'is': 623, 'really': 930, 'quiet': 916, 'outcome': 801, 'based': 114, 'education': 325, 'teaches': 1110, 'thinking': 1142, 'skills': 1024, 'and': 58, 'engages': 353, 'students': 1069, 'more': 734, 'when': 1229, 'student': 1068, 'product': 882, 'in': 577, 'much': 740, 'meaningful': 710, 'than': 1123, 'answers': 62, 'test': 1120, 'provides': 906, 'learning': 659, 'similar': 1015, 'real': 927, 'world': 1255, 'applications': 67, 'with': 1245, 'sense': 990, 'instructors': 607, 'will': 1240, 'able': 5, 'structure': 1065, 

In [ ]:
bag_of_words=vect.transform(words)


In [ ]:
print(bag_of_words)



  (0, 993)	1
  (0, 995)	1
  (1, 501)	1
  (1, 627)	1
  (2, 157)	1
  (2, 634)	1
  (2, 899)	1
  (2, 1090)	1
  (2, 1109)	1
  (2, 1144)	1
  (2, 1148)	1
  (2, 1197)	1
  (3, 11)	1
  (3, 121)	1
  (3, 154)	1
  (3, 184)	1
  (3, 229)	1
  (3, 235)	1
  (3, 348)	1
  (3, 406)	1
  (3, 455)	1
  (3, 751)	1
  (3, 771)	2
  (3, 776)	1
  (3, 802)	1
  :	:
  (596, 623)	1
  (596, 771)	2
  (596, 794)	1
  (596, 801)	1
  (596, 814)	1
  (596, 840)	1
  (596, 870)	1
  (596, 961)	1
  (596, 1126)	2
  (597, 55)	1
  (597, 97)	1
  (597, 207)	1
  (597, 232)	1
  (597, 243)	1
  (597, 325)	1
  (597, 577)	1
  (597, 623)	1
  (597, 627)	1
  (597, 718)	1
  (597, 771)	1
  (597, 852)	1
  (597, 904)	1
  (597, 1153)	1
  (597, 1173)	1
  (597, 1209)	1


In [ ]:
print("bag_of_worda as array:\n{}".format(bag_of_words.toarray()))

bag_of_worda as array:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
vect.get_feature_names()

['01st',
 '10',
 '15',
 'abilities',
 'ability',
 'able',
 'about',
 'abroad',
 'absorb',
 'academic',
 'accept',
 'accomplished',
 'accountability',
 'accreditation',
 'achieve',
 'achieved',
 'achievement',
 'achieving',
 'achive',
 'acquired',
 'actual',
 'actually',
 'adapts',
 'add',
 'added',
 'adding',
 'addition',
 'addressing',
 'administrative',
 'administrators',
 'admiring',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'advance',
 'advantage',
 'advantages',
 'afraid',
 'after',
 'again',
 'age',
 'agree',
 'aimed',
 'all',
 'allow',
 'allows',
 'along',
 'already',
 'alright',
 'also',
 'always',
 'am',
 'amazing',
 'among',
 'an',
 'analysis',
 'analyze',
 'and',
 'another',
 'answer',
 'answering',
 'answers',
 'any',
 'anything',
 'appeal',
 'application',
 'applications',
 'applied',
 'applies',
 'apply',
 'applying',
 'appreciate',
 'approach',
 'approaches',
 'appropriate',
 'approval',
 'are',
 'argued',
 'around',
 'arranging',
 'articulate',
 'as',
 'aspects',
 

In [ ]:
data =pd.read_csv('/content/drive/My Drive/Colab Notebooks/Thesis Data test.csv')

In [ ]:
data.head()

Sentence  sentiment
0                                         It's good.          1
1  teachers can judge us properly through this sy...          1
2  The focus on outcomes creates a clear expectat...          0
3                             Not a good curriculum.          0
4                        This system is really good.          1

In [ ]:
X = data['Sentence']
y= data['sentiment']

In [ ]:
print(y.shape)
print(X.shape)

(596,)
(596,)


In [ ]:
vectorizer = CountVectorizer()


In [ ]:
X_train,X_test,y_train, y_test = train_test_split( X, y, test_size = 0.2)


In [ ]:
len(X_train)

476

In [ ]:
print("sample class: {}".format(np.bincount(y_train)))
print("sample class: {}".format(np.bincount(y_test)))

sample class: [190 286]
sample class: [53 67]


In [ ]:
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [ ]:
feature_names = vectorizer.get_feature_names()
print("number of features: {}".format(len(feature_names)))

number of features: 1115


In [ ]:
scores = cross_val_score(LogisticRegression(), X_train,y_train, cv=5)
print("Mean Cross Validation Accuracy: {:.2f}".format(np.mean(scores)) )

Mean Cross Validation Accuracy: 0.74


In [ ]:
logreg= LogisticRegression()
logreg.fit(X_train,y_train)
print("train Score: {:.3f}".format(logreg.score(X_train,y_train)))
print("test Score: {:.3f}".format(logreg.score(X_test,y_test)))

train Score: 0.977
test Score: 0.708


In [ ]:
pred_logreg  = logreg.predict(X_test)
confusion = confusion_matrix(y_test,pred_logreg)
print("cofusion Matrix:\n{}" .format(confusion))

cofusion Matrix:
[[30 23]
 [12 55]]


In [ ]:
nb = MultinomialNB()
nb.fit(X_train,y_train)
print("Training set score: {:.3f}".format(nb.score(X_train,y_train)))
print("Test set score: {:.3f}".format(nb.score(X_test,y_test)))

Training set score: 0.933
Test set score: 0.700


In [ ]:
pred_nb  = nb.predict(X_test)
confusion = confusion_matrix(y_test,pred_nb)
print("cofusion Matrix:\n{}" .format(confusion)) 

cofusion Matrix:
[[31 22]
 [14 53]]


In [ ]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
print("Training set score: {:.3f}".format(nb.score(X_train,y_train)))
print("Test set score: {:.3f}".format(nb.score(X_test,y_test)))

Training set score: 0.933
Test set score: 0.700


In [ ]:
pred_rf  = rf.predict(X_test)
confusion = confusion_matrix(y_test,pred_rf)
print("cofusion Matrix:\n{}" .format(confusion))

cofusion Matrix:
[[24 29]
 [ 8 59]]


In [ ]:
review = "OBE is not good"
print(logreg.predict(vectorizer.transform([review]))[0])
print(rf.predict(vectorizer.transform([review]))[0])
print(nb.predict(vectorizer.transform([review]))[0])

0
0
0


In [ ]:
rev = "wish i could say something good but i cant because its too bad"
print(logreg.predict(vectorizer.transform([rev]))[0])
print(rf.predict(vectorizer.transform([rev]))[0])
print(nb.predict(vectorizer.transform([rev]))[0])

1
1
0
